// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySqlDemo.Persistence;

#nullable disable

namespace MySqlDemo.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20221206120423_VW_Cars_And_Colors")]
    partial class VW_Cars_And_Colors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MySqlDemo.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Brand1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brand2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brand3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brand4"
                        });
                });

            modelBuilder.Entity("MySqlDemo.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ColorId = 1,
                            Name = "Car1"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            ColorId = 2,
                            Name = "Car2"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            ColorId = 3,
                            Name = "Car3"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            ColorId = 4,
                            Name = "Car4"
                        });
                });

            modelBuilder.Entity("MySqlDemo.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "ColorHex1",
                            ColorName = "ColorName1"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "ColorHex2",
                            ColorName = "ColorName2"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "ColorHex3",
                            ColorName = "ColorName3"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "ColorHex4",
                            ColorName = "ColorName4"
                        });
                });

            modelBuilder.Entity("MySqlDemo.Models.Car", b =>
                {
                    b.HasOne("MySqlDemo.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySqlDemo.Models.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("MySqlDemo.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("MySqlDemo.Models.Color", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
